---
apiVersion: v1
kind: Service
metadata:
  name: tactica-auth
  labels:
    app.kubernetes.io/name: tactica
    tactica.gg/service: auth
spec:
  selector:
    app.kubernetes.io/name: tactica
    tactica.gg/service: auth
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: tactica-gateway
  labels:
    app.kubernetes.io/name: tactica
    tactica.gg/service: gateway
spec:
  selector:
    app.kubernetes.io/name: tactica
    tactica.gg/service: gateway
  ports:
    - name: grpc
      port: 50050
      protocol: TCP
      targetPort: 50050
