name: tactica
type: laravel
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
  # needed for multitenancy
  - '*.tactica'
additional_fqdns: []
database:
    type: postgres
    version: '18'
use_dns_when_possible: true
composer_version: "2"

web_environment:
  - VITE_SERVER_URI=https://vite.tactica.ddev.site
  - VITE_PACKAGE_MANAGER=bun

web_extra_daemons:
  - name: vite
    command: bash -c 'bun run dev'
    directory: /var/www/html
