name: tactica
type: laravel
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
  # needed for multitenancy
  - '*.tactica'
additional_fqdns: []
database:
    type: postgres
    version: '18'
use_dns_when_possible: true
composer_version: "2"
