---
name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2
      - name: Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo build
        run: cargo build --bin tactica

      - name: Cargo build (release)
        run: cargo build --bin tactica --release

      - name: Upload binaries (debug)
        id: upload-debug
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: tactica-debug-linux-amd64
          path: target/debug/tactica

      - uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2
        with:
          subject-name: tactica-debug-linux-amd64
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

      - name: Upload binaries (release)
        id: upload-release
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: tactica-release-linux-amd64
          path: target/release/tactica

      - uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2
        with:
          subject-name: tactica-release-linux-amd64
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
