---
name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test

  build-debug:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SERVICE: [auth]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo build
        run: cargo build --bin tactica-svc-${{ matrix.SERVICE }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.SERVICE }}-debug-linux-amd64
          path: target/debug/tactica-svc-${{ matrix.SERVICE }}

  build-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SERVICE: [auth]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo build
        run: cargo build --bin tactica-svc-${{ matrix.SERVICE }} --release

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.SERVICE }}-linux-amd64
          path: target/release/tactica-svc-${{ matrix.SERVICE }}
