name: linter

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: write

jobs:
  quality-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up repo
        uses: ./.github/actions/setup-repo

      - name: Format Frontend
        run: ddev bun run format:check

      - name: Lint Frontend
        run: ddev bun run lint:check

  quality-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up repo
        uses: ./.github/actions/setup-repo

      - name: Run Pint
        run: ddev composer run lint:check
