name: tests

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: ./.github/actions/setup-repo
        with:
          include-frontend: 'false'

      - name: Tests
        run: ddev php artisan test
